# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username:
  password:

development:
  <<: *default
  database: BornHussaApp_development

test:
  <<: *default
  database: BornHussaApp_test

production:
  <<: *default
  database: BornHussaApp_production
  username: BornHussaApp
  password: <%= ENV['HELLOAPP_DATABASE_PASSWORD'] %>
